# Generated by Django 5.0.6 on 2024-06-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='backend\recipe_realm\\image\\defualt.jpeg', upload_to=''),
        ),
    ]
